# Generated by Django 5.0 on 2023-12-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Title', models.CharField(max_length=255)),
                ('Income', models.BooleanField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.counterparty')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_in_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Income', models.BooleanField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.documents')),
                ('Good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.good')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Income', models.BooleanField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.counterparty')),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.documents')),
                ('Good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri.good')),
            ],
        ),
    ]
