# Generated by Django 5.0 on 2024-01-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0002_documents_goods_in_stock_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='Income',
        ),
        migrations.AddField(
            model_name='documents',
            name='Doctype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ri.doctype'),
        ),
    ]
