# Generated by Django 5.0 on 2024-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0004_alter_counterparty_options_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
